<html>
    <head>
        <title>Admin: Find Revenue Generated By</title>
    </head>
    <body>        
        <form method="post" action="revenueGeneratedByB.jsp">
           <table>
               <tr>
                   <td>Find revenue generated by: </td>
                   <td>
                        <select name="action" size=1 required>
                            <option value="1">flight.</option>
                            <option value="2">airline.</option>
                            <option value="3">customer.</option>
                        </select>
                    </td>
               </tr>

               <tr>
                   <td>Enter the value to be searched for: </td>
                   <td> <input type="text" name="searchValue" required></td>
               </tr>
           </table> 

            <input type="submit" value="submit">
	    </form>
    </body>
</html>