<html>
    <head>
        <title>Admin: Find Revenue Generated By Flight</title>
    </head>
    <body>        
        <form method="post" action="rGBFlightB.jsp">
           <table>
               <tr>
                   <td>Enter the flight number: </td>
                   <td><input type="text" name="flightNumber" required></td>
               </tr>

               <tr>
                   <td>Enter the airline of the flight: </td>
                   <td> <input type="text" name="airline" required></td>
               </tr>
           </table> 

            <input type="submit" value="submit">
	    </form>
    </body>
</html>