<%@ page import ="java.io.*,java.util.*,java.sql.*,java.lang.*" %>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<html>
    <head>
        <title>Admin: Find Revenue Generated By</title>
    </head>
    <body>
        <%
        String url = "jdbc:mysql://project.cvxoxmir4k3m.us-east-2.rds.amazonaws.com:3306/Project";
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        connection = DriverManager.getConnection(url, "Application", "JAAYS");

        String action = request.getParameter("action");

        if(action.equals("1")) { //by flight
            response.sendRedirect("rGBFlight.jsp");
        }

        else if(action.equals("2")) { //by airline
            response.sendRedirect("rGBAirline.jsp");
        }

        else if(action.equals("3")) { //by customer
            response.sendRedirect("rGBCustomer.jsp");
        }
	%>
    </body>
</html>