<%@ page import ="java.io.*,java.util.*,java.sql.*,java.lang.*" %>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<html>
    <head>
        <title>Admin: Find Revenue Generated By</title>
    </head>
    <body>
        <%
        String url = "jdbc:mysql://project.cvxoxmir4k3m.us-east-2.rds.amazonaws.com:3306/Project";
        Connection connection = null;
        PreparedStatement preparedStatement = null;
		try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            connection = DriverManager.getConnection(url, "Application", "JAAYS");

            String airline = request.getParameter("airline");
            String q;
            PreparedStatement ps;
            ResultSet rs;
            int outcome = 0;
            
            q = "SELECT count(*) FROM Airline a WHERE airlineID = ?";
            
            ps = connection.prepareStatement(q);
            ps.setString(1, airline);
            
            rs = ps.executeQuery();
            rs.next();
            String cnt = rs.getString(1);

            if (!cnt.equals("0")){
                q = "SELECT a.airlineID, t.bookingFee FROM Airline a, Flight f, TicketFor tf, Ticket t WHERE f.flightNumber = tf.flightNumber AND tf.ticketNumber = t.ticketNumber AND f.flightNumber = ? AND f.airlineID = a.airlineID AND a.airlineID = ?";

                ps = connection.prepareStatement(q);
                ps.setString(1, airline);

                rs = ps.executeQuery();

                %>
                <table>
                    <tr>
                        <td width = 200px>Airline</td>
                        <td width = 500px>Amount of Each Ticket</td>
                    </tr>
                <%
                while (rs.next()) {
                %>
                    <tr>
                        <td>
                            <%=rs.getString("a.airlineID")%>
                        </td>
                        <td>
                            <%=rs.getFloat("t.bookingFee")%>
                        </td>
                    </tr>
                <%
                }
                q = "SELECT SUM(t.bookingFee) FROM Airline a, Flight f, TicketFor tf, Ticket t WHERE f.flightNumber = tf.flightNumber AND tf.ticketNumber = t.ticketNumber AND f.flightNumber = ? AND f.airlineID = a.airlineID AND a.airlineID = ?";
                
                ps = connection.prepareStatement(q);
                ps.setString(1, airline);
                rs = ps.executeQuery();
                %>
                    <tr padding = 10px 0px 0px>
                            <td>Total Sales:</td>
                            <td><%=rs.getFloat("SUM(t.bookingFee)")%></td>
                    </tr>
                </table>
            <%
            }

            else {
                out.println("The customer you're searching for does not exist, <a href = 'rGBAirline.jsp'>please try again.</a>");
            }
	    } catch (Exception e) {
			out.print(e);
		}
	%>
    </body>
</html>