<html>
    <head>
        <title>Admin: Find Revenue Generated By Airline</title>
    </head>
    <body>        
        <form method="post" action="rGBAirlineB.jsp">
           <table>
               <tr>
                   <td>Enter the airline: </td>
                   <td> <input type="text" name="airline" required></td>
               </tr>
           </table> 

            <input type="submit" value="submit">
	    </form>
    </body>
</html>