<%@ page import ="java.io.*,java.util.*,java.sql.*,java.lang.*" %>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<html>
    <head>
        <title>Admin: Find Revenue Generated By</title>
    </head>
    <body>
        <%
        String url = "jdbc:mysql://project.cvxoxmir4k3m.us-east-2.rds.amazonaws.com:3306/Project";
        Connection connection = null;
        PreparedStatement preparedStatement = null;
		try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            connection = DriverManager.getConnection(url, "Application", "JAAYS");

            String action = request.getParameter("action");
            String username = request.getParameter("username");
            String q;
            PreparedStatement ps;
            ResultSet rs;

            q = "SELECT count(*) FROM Person p, Customer c WHERE p.username = c.username AND p.username = ?";

            ps = connection.prepareStatement(q);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            rs.next();
            String cnt = rs.getString(1);

            if (!cnt.equals("0")){ //customer exists
                q = "SELECT c.username, t.bookingFee FROM Customer c, Buy b, Ticket t WHERE c.username = b.username AND b.ticketNumber = t.ticketNumber AND c.username = ?";
                ps = connection.prepareStatement(q);
                ps.setString(1, username);
                
                rs = ps.executeQuery();
                %>
                <table>
                    <tr>
                        <td width = 200px>Customer</td>
                        <td width = 500px>Amount of Each Ticket</td>
                    </tr>
                <%
                while (rs.next()) {
                %>
                    <tr>
                        <td>
                            <%=rs.getString("f.airlineID")%>
                        </td>
                        <td>
                            <%=rs.getFloat("t.bookingFee")%>
                        </td>
                    </tr>
                <%
                }
                q = "SELECT SUM(t.bookingFee) FROM Customer c, Buy b, Ticket t WHERE c.username = b.username AND b.ticketNumber = t.ticketNumber AND c.username = ?";
                ps = connection.prepareStatement(q);
                ps.setString(1, username);
                try {
                    rs = ps.executeQuery();
                }
                catch (Exception e) {
                    out.print(e);
                }

                %>
                <tr padding = 10px 0px 0px>
                        <td>Total Sales of Airline:</td>
                        <td><%=rs.getFloat("SUM(t.bookingFee)")%></td>
                    </tr>
                </table>
                <%
            }

            else {
                out.println("The customer you're searching for does not exist, <a href = 'rGBCustomer.jsp'>please try again.</a>");
            }
	    } catch (Exception e) {
			out.print(e);
		}
	%>
    </body>
</html>