<html>
    <head>
        <title>Admin: Find Revenue Generated By</title>
    </head>
    <body>        
        <form method="post" action="revenueGeneratedByB.jsp">
           <table>
                <tr>
                    <td>Find the revenue generated by a(n): </td>
                   
                    <td>
                        <select name="action" size=1 required>
                            <option value="1">flight</option>
                            <option value="2">airline</option>
                            <option value="3">customer</option>
                        </select>
                    </td>
                </tr>
                <tr><td><input type="submit" value="submit"></td></tr>
            </table>
	    </form>
    </body>
</html>